// Code generated by goyacc -o ./src/parser/n.y.go -p n ./src/parser/n.y. DO NOT EDIT.

//line ./src/parser/n.y:8
package parser

import __yyfmt__ "fmt"

//line ./src/parser/n.y:8

import (
	"nlang/src/ast"
)

var Ast ast.NLang

//line ./src/parser/n.y:16
type nSymType struct {
	yys            int
	id             string
	number         int
	value          ast.Value
	value_list     []ast.Value
	value_type     ast.ValueType
	assignment     ast.Assignment
	argument_list  []ast.Argument
	argument       ast.Argument
	function       ast.Function
	function_list  []ast.Function
	block          ast.Block
	block_list     []ast.Block
	caller         ast.Caller
	statement      ast.Statement
	statement_list []ast.Statement
}

const ID = 57346
const STRING_LITERAL = 57347
const SQL_LITERAL = 57348
const INT_LITERAL = 57349
const ASSIGN = 57350
const FUNC = 57351
const EOL = 57352
const STRING = 57353
const INT = 57354
const FLOAT = 57355
const BOOL = 57356
const SQL = 57357

var nToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ID",
	"STRING_LITERAL",
	"SQL_LITERAL",
	"INT_LITERAL",
	"ASSIGN",
	"FUNC",
	"EOL",
	"STRING",
	"INT",
	"FLOAT",
	"BOOL",
	"SQL",
	"'{'",
	"'}'",
	"'('",
	"')'",
	"','",
}

var nStatenames = [...]string{}

const nEofCode = 1
const nErrCode = 2
const nInitialStackSize = 16

//line ./src/parser/n.y:188

//line yacctab:1
var nExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const nPrivate = 57344

const nLast = 62

var nAct = [...]int8{
	23, 38, 27, 5, 31, 39, 13, 28, 24, 25,
	26, 50, 49, 44, 45, 14, 15, 16, 17, 18,
	36, 12, 41, 35, 34, 33, 32, 29, 22, 3,
	11, 35, 40, 7, 10, 21, 43, 47, 9, 12,
	20, 39, 34, 33, 32, 48, 46, 51, 19, 1,
	52, 28, 24, 25, 26, 2, 42, 30, 37, 6,
	8, 4,
}

var nPact = [...]int16{
	29, -1000, 24, -1000, -1000, -1000, 14, 31, 4, 44,
	29, 18, 47, -1000, -1000, -1000, -1000, -1000, -1000, 9,
	-1000, -1000, 38, -1000, -1000, -1000, -1000, -1000, 5, 1,
	22, -1000, -1000, -1000, 13, 3, -1000, -6, -1000, 4,
	20, -1000, -8, -1000, -1000, 37, -1000, -1000, -1000, 47,
	-1000, -1000, -1000,
}

var nPgo = [...]int8{
	0, 0, 3, 6, 61, 60, 59, 1, 58, 4,
	57, 2, 56, 29, 55, 49,
}

var nR1 = [...]int8{
	0, 15, 13, 13, 14, 14, 4, 4, 6, 6,
	5, 5, 10, 10, 9, 9, 8, 8, 7, 2,
	1, 1, 1, 1, 1, 12, 12, 3, 3, 3,
	3, 3, 11, 11,
}

var nR2 = [...]int8{
	0, 1, 1, 1, 1, 3, 3, 6, 1, 2,
	4, 5, 1, 3, 1, 1, 1, 3, 2, 3,
	1, 1, 1, 1, 1, 1, 3, 1, 1, 1,
	1, 1, 3, 4,
}

var nChk = [...]int16{
	-1000, -15, -14, -13, -4, -2, -6, 4, -5, 9,
	10, 16, 8, -3, 11, 12, 13, 14, 15, 4,
	-13, 17, 10, -1, 5, 6, 7, -11, 4, 18,
	-10, -9, -2, -11, 4, 18, 19, -8, -7, 4,
	10, 19, -12, -1, 19, 20, -3, 17, -9, 20,
	19, -7, -1,
}

var nDef = [...]int8{
	0, -2, 1, 4, 2, 3, 0, 0, 8, 0,
	0, 0, 0, 9, 27, 28, 29, 30, 31, 0,
	5, 6, 0, 19, 20, 21, 22, 23, 24, 0,
	0, 12, 14, 15, 0, 0, 10, 0, 16, 0,
	0, 32, 0, 25, 11, 0, 18, 7, 13, 0,
	33, 17, 26,
}

var nTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	18, 19, 3, 3, 20, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 16, 3, 17,
}

var nTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15,
}

var nTok3 = [...]int8{
	0,
}

var nErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	nDebug        = 0
	nErrorVerbose = false
)

type nLexer interface {
	Lex(lval *nSymType) int
	Error(s string)
}

type nParser interface {
	Parse(nLexer) int
	Lookahead() int
}

type nParserImpl struct {
	lval  nSymType
	stack [nInitialStackSize]nSymType
	char  int
}

func (p *nParserImpl) Lookahead() int {
	return p.char
}

func nNewParser() nParser {
	return &nParserImpl{}
}

const nFlag = -1000

func nTokname(c int) string {
	if c >= 1 && c-1 < len(nToknames) {
		if nToknames[c-1] != "" {
			return nToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func nStatname(s int) string {
	if s >= 0 && s < len(nStatenames) {
		if nStatenames[s] != "" {
			return nStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func nErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !nErrorVerbose {
		return "syntax error"
	}

	for _, e := range nErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + nTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(nPact[state])
	for tok := TOKSTART; tok-1 < len(nToknames); tok++ {
		if n := base + tok; n >= 0 && n < nLast && int(nChk[int(nAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if nDef[state] == -2 {
		i := 0
		for nExca[i] != -1 || int(nExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; nExca[i] >= 0; i += 2 {
			tok := int(nExca[i])
			if tok < TOKSTART || nExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if nExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += nTokname(tok)
	}
	return res
}

func nlex1(lex nLexer, lval *nSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(nTok1[0])
		goto out
	}
	if char < len(nTok1) {
		token = int(nTok1[char])
		goto out
	}
	if char >= nPrivate {
		if char < nPrivate+len(nTok2) {
			token = int(nTok2[char-nPrivate])
			goto out
		}
	}
	for i := 0; i < len(nTok3); i += 2 {
		token = int(nTok3[i+0])
		if token == char {
			token = int(nTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(nTok2[1]) /* unknown char */
	}
	if nDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", nTokname(token), uint(char))
	}
	return char, token
}

func nParse(nlex nLexer) int {
	return nNewParser().Parse(nlex)
}

func (nrcvr *nParserImpl) Parse(nlex nLexer) int {
	var nn int
	var nVAL nSymType
	var nDollar []nSymType
	_ = nDollar // silence set and not used
	nS := nrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	nstate := 0
	nrcvr.char = -1
	ntoken := -1 // nrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		nstate = -1
		nrcvr.char = -1
		ntoken = -1
	}()
	np := -1
	goto nstack

ret0:
	return 0

ret1:
	return 1

nstack:
	/* put a state and value onto the stack */
	if nDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", nTokname(ntoken), nStatname(nstate))
	}

	np++
	if np >= len(nS) {
		nyys := make([]nSymType, len(nS)*2)
		copy(nyys, nS)
		nS = nyys
	}
	nS[np] = nVAL
	nS[np].yys = nstate

nnewstate:
	nn = int(nPact[nstate])
	if nn <= nFlag {
		goto ndefault /* simple state */
	}
	if nrcvr.char < 0 {
		nrcvr.char, ntoken = nlex1(nlex, &nrcvr.lval)
	}
	nn += ntoken
	if nn < 0 || nn >= nLast {
		goto ndefault
	}
	nn = int(nAct[nn])
	if int(nChk[nn]) == ntoken { /* valid shift */
		nrcvr.char = -1
		ntoken = -1
		nVAL = nrcvr.lval
		nstate = nn
		if Errflag > 0 {
			Errflag--
		}
		goto nstack
	}

ndefault:
	/* default state action */
	nn = int(nDef[nstate])
	if nn == -2 {
		if nrcvr.char < 0 {
			nrcvr.char, ntoken = nlex1(nlex, &nrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if nExca[xi+0] == -1 && int(nExca[xi+1]) == nstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			nn = int(nExca[xi+0])
			if nn < 0 || nn == ntoken {
				break
			}
		}
		nn = int(nExca[xi+1])
		if nn < 0 {
			goto ret0
		}
	}
	if nn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			nlex.Error(nErrorMessage(nstate, ntoken))
			Nerrs++
			if nDebug >= 1 {
				__yyfmt__.Printf("%s", nStatname(nstate))
				__yyfmt__.Printf(" saw %s\n", nTokname(ntoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for np >= 0 {
				nn = int(nPact[nS[np].yys]) + nErrCode
				if nn >= 0 && nn < nLast {
					nstate = int(nAct[nn]) /* simulate a shift of "error" */
					if int(nChk[nstate]) == nErrCode {
						goto nstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if nDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", nS[np].yys)
				}
				np--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if nDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", nTokname(ntoken))
			}
			if ntoken == nEofCode {
				goto ret1
			}
			nrcvr.char = -1
			ntoken = -1
			goto nnewstate /* try again in the same state */
		}
	}

	/* reduction by production nn */
	if nDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", nn, nStatname(nstate))
	}

	nnt := nn
	npt := np
	_ = npt // guard against "declared and not used"

	np -= int(nR2[nn])
	// np is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if np+1 >= len(nS) {
		nyys := make([]nSymType, len(nS)*2)
		copy(nyys, nS)
		nS = nyys
	}
	nVAL = nS[np+1]

	/* consult goto table to find next state */
	nn = int(nR1[nn])
	ng := int(nPgo[nn])
	nj := ng + nS[np].yys + 1

	if nj >= nLast {
		nstate = int(nAct[ng])
	} else {
		nstate = int(nAct[nj])
		if int(nChk[nstate]) != -nn {
			nstate = int(nAct[ng])
		}
	}
	// dummy call; replaced with literal code
	switch nnt {

	case 1:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:55
		{
			Ast = ast.NLang{Statements: nDollar[1].statement_list}
		}
	case 2:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:61
		{
			nVAL.statement = ast.Statement{Type: ast.FunctionStatement, Value: nDollar[1].function}
		}
	case 3:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:64
		{
			nVAL.statement = ast.Statement{Type: ast.AssignmentStatement, Value: nDollar[1].assignment}
		}
	case 4:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:70
		{
			nVAL.statement_list = []ast.Statement{nDollar[1].statement}
		}
	case 5:
		nDollar = nS[npt-3 : npt+1]
//line ./src/parser/n.y:73
		{
			nVAL.statement_list = append(nDollar[1].statement_list, nDollar[3].statement)
		}
	case 6:
		nDollar = nS[npt-3 : npt+1]
//line ./src/parser/n.y:79
		{
			nVAL.function = nDollar[1].function
		}
	case 7:
		nDollar = nS[npt-6 : npt+1]
//line ./src/parser/n.y:82
		{
			nDollar[1].function.Blocks = nDollar[4].block_list
			nVAL.function = nDollar[1].function
		}
	case 8:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:88
		{
			nVAL.function = nDollar[1].function
		}
	case 9:
		nDollar = nS[npt-2 : npt+1]
//line ./src/parser/n.y:91
		{
			nDollar[1].function.Type = nDollar[2].value_type
			nVAL.function = nDollar[1].function
		}
	case 10:
		nDollar = nS[npt-4 : npt+1]
//line ./src/parser/n.y:98
		{
			nVAL.function = ast.Function{Name: nDollar[2].id}
		}
	case 11:
		nDollar = nS[npt-5 : npt+1]
//line ./src/parser/n.y:101
		{
			nVAL.function = ast.Function{Name: nDollar[2].id, Args: nDollar[4].argument_list}
		}
	case 12:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:107
		{
			nVAL.block_list = []ast.Block{nDollar[1].block}
		}
	case 13:
		nDollar = nS[npt-3 : npt+1]
//line ./src/parser/n.y:110
		{
			nVAL.block_list = append(nDollar[1].block_list, nDollar[3].block)
		}
	case 14:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:116
		{
			nVAL.block = ast.Block{Type: ast.AssignmentBlock, Value: nDollar[1].assignment}
		}
	case 15:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:119
		{
			nVAL.block = ast.Block{Type: ast.CallerBlock, Value: nDollar[1].caller}
		}
	case 16:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:125
		{
			nVAL.argument_list = []ast.Argument{nDollar[1].argument}
		}
	case 17:
		nDollar = nS[npt-3 : npt+1]
//line ./src/parser/n.y:128
		{
			nVAL.argument_list = append(nDollar[1].argument_list, nDollar[3].argument)
		}
	case 18:
		nDollar = nS[npt-2 : npt+1]
//line ./src/parser/n.y:134
		{
			nVAL.argument = ast.Argument{Name: nDollar[1].id, Type: nDollar[2].value_type}
		}
	case 19:
		nDollar = nS[npt-3 : npt+1]
//line ./src/parser/n.y:140
		{
			nVAL.assignment = ast.Assignment{Variable: nDollar[1].id, Value: nDollar[3].value}
		}
	case 20:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:146
		{
			nVAL.value = ast.Value{Type: ast.StringType, Value: nDollar[1].id}
		}
	case 21:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:149
		{
			nVAL.value = ast.Value{Type: ast.SQLType, Value: nDollar[1].id}
		}
	case 22:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:152
		{
			nVAL.value = ast.Value{Type: ast.IntType, Value: nDollar[1].number}
		}
	case 23:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:155
		{
			nVAL.value = ast.Value{Type: ast.CallerType, Value: nDollar[1].caller}
		}
	case 24:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:158
		{
			nVAL.value = ast.Value{Type: ast.VariableType, Value: nDollar[1].id}
		}
	case 25:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:164
		{
			nVAL.value_list = []ast.Value{nDollar[1].value}
		}
	case 26:
		nDollar = nS[npt-3 : npt+1]
//line ./src/parser/n.y:167
		{
			nVAL.value_list = append(nDollar[1].value_list, nDollar[3].value)
		}
	case 27:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:173
		{
			nVAL.value_type = ast.StringType
		}
	case 28:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:174
		{
			nVAL.value_type = ast.IntType
		}
	case 29:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:175
		{
			nVAL.value_type = ast.FloatType
		}
	case 30:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:176
		{
			nVAL.value_type = ast.BoolType
		}
	case 31:
		nDollar = nS[npt-1 : npt+1]
//line ./src/parser/n.y:177
		{
			nVAL.value_type = ast.SQLType
		}
	case 32:
		nDollar = nS[npt-3 : npt+1]
//line ./src/parser/n.y:181
		{
			nVAL.caller = ast.Caller{Name: nDollar[1].id}
		}
	case 33:
		nDollar = nS[npt-4 : npt+1]
//line ./src/parser/n.y:184
		{
			nVAL.caller = ast.Caller{Name: nDollar[1].id, Values: nDollar[3].value_list}
		}
	}
	goto nstack /* stack new state and value */
}
